#include "help.h"

#include <stdio.h>

void help_print(void) {
    fprintf(stdout,
        "qbdbg - a lightweight x86-64 debugger\n"
        "\n"
        "USAGE\n"
        "    qbdbg [options] [program [args...]]\n"
        "\n"
        "OPTIONS\n"
        "    -h, --help          Print this help message and exit\n"
        "\n"
        "    If a program path is given, qbdbg will launch and attach to it\n"
        "    immediately, passing any trailing arguments to the target:\n"
        "\n"
        "        qbdbg /usr/bin/ls -l -a\n"
        "        qbdbg -- /usr/bin/ls -l -a     (use -- to be explicit)\n"
        "\n"
        "COMMANDS\n"
        "    Process control\n"
        "        launch <program> [args...]      Launch and attach to a program\n"
        "        continue                        Resume execution of the target\n"
        "        quit                            Detach and exit the debugger\n"
        "\n"
        "    Breakpoints\n"
        "        break <addr> [addr...]          Set a breakpoint at one or more\n"
        "                                        addresses (hex: 0x400100)\n"
        "\n"
        "    Stepping\n"
        "        si                              Step into  - execute one instruction,\n"
        "                                        following calls\n"
        "        sov                             Step over  - execute one instruction,\n"
        "                                        stepping over calls\n"
        "        so                              Step out   - run until the current\n"
        "                                        function returns\n"
        "\n"
        "    Registers\n"
        "        rg                              Print all registers\n"
        "        rg <reg> [reg...]               Print one or more specific registers\n"
        "        rs <reg> <value>                Set a register to a value\n"
        "\n"
        "        Available registers:\n"
        "            rip  rsp  rbp  rbx\n"
        "            rax  rcx  rdx  rsi  rdi\n"
        "            r8   r9   r10  r11  r12  r13  r14  r15\n"
        "            cs   ss   ds   es   fs   gs\n"
        "            eflags  (CF PF AF ZF SF TF IF DF OF)\n"
        "\n"
        "NOTES\n"
        "    - Breakpoint addresses can be decimal, hex (0x...), or octal (0...).\n"
        "      Prefer hex to avoid accidental octal interpretation.\n"
        "    - Up to 128 breakpoints can be active at once.\n"
        "    - Command history is saved to .qbdbg_history across sessions.\n"
    );
}
